### ISSUE TITLE
Redundant button and Incomplete Experiment 2.

### ISSUE THREAD

**Issue by nisargshahh** [nisargshahh/vortex#6]
There's no code as mentioned in the experiment. Edit the same.
<img width="504" alt="Screenshot 2023-06-28 164809" src="https://github.com/nisargshahh/vortex/assets/81844922/cd35166f-e0ac-48b8-860e-cea49ee0a8d5">

**Comment by nisargshahh** [comment]
> Hi @nisargshahh does this mean the button to "go to simulation" is not required on this page?

It does mean that, and we are supposed to have a python file displayed there, so we are finding ways or platforms to integrate that preferably through a JS library, or an iframe. Suggestions for the same are appreciated.

**Comment by temideewan** [comment]
have you considered using [react-code-blocks](https://www.npmjs.com/package/react-code-blocks) instead

**Comment by nisargshahh** [comment]
> have you considered using [react-code-blocks](https://www.npmjs.com/package/react-code-blocks) instead

that is a great choice!
